import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { LineItem } from "@/lib/invoice/calc";

export type ReceiptData = {
  invoiceNumber: string;
  status: string;
  paidAt: string | null;
  issuedAt: string;
  serviceName: string;
  customerName: string;
  address: string | null;
  lineItems: LineItem[];
  subtotalCents: number;
  gstCents: number;
  totalCents: number;
};

const BUSINESS = {
  name: "ModernHome",
  abn: "ABN 00 000 000 000",
  email: "hello@modernhome.com.au",
  region: "Servicing Greater Melbourne",
};

const aud = (cents: number) =>
  `$${(cents / 100).toLocaleString("en-AU", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, color: "#1c1917", fontFamily: "Helvetica" },
  row: { flexDirection: "row", justifyContent: "space-between" },
  brand: { fontSize: 20, fontFamily: "Helvetica-Bold" },
  muted: { color: "#78716c" },
  h: { fontSize: 14, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  paidBadge: {
    marginTop: 6,
    alignSelf: "flex-start",
    color: "#166534",
    backgroundColor: "#dcfce7",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
    fontFamily: "Helvetica-Bold",
  },
  table: { marginTop: 8, borderTopWidth: 1, borderTopColor: "#e7e5e4" },
  th: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e7e5e4",
    paddingVertical: 6,
    color: "#78716c",
    fontFamily: "Helvetica-Bold",
  },
  tr: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f4",
    paddingVertical: 6,
  },
  cDesc: { flex: 1 },
  cQty: { width: 50, textAlign: "right" },
  cUnit: { width: 80, textAlign: "right" },
  cAmt: { width: 80, textAlign: "right" },
  totals: { marginTop: 12, alignSelf: "flex-end", width: 220 },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 },
  grand: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 6,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: "#e7e5e4",
    fontFamily: "Helvetica-Bold",
    fontSize: 12,
  },
  footer: { marginTop: 40, color: "#a8a29e", fontSize: 8 },
});

/** Branded A4 receipt/invoice document. */
export function ReceiptDocument({ data }: { data: ReceiptData }) {
  const paid = data.status === "paid";
  return (
    <Document title={data.invoiceNumber}>
      <Page size="A4" style={s.page}>
        <View style={s.row}>
          <View>
            <Text style={s.brand}>{BUSINESS.name}</Text>
            <Text style={s.muted}>{BUSINESS.abn}</Text>
            <Text style={s.muted}>{BUSINESS.region}</Text>
            <Text style={s.muted}>{BUSINESS.email}</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={s.h}>{paid ? "Receipt" : "Tax Invoice"}</Text>
            <Text>{data.invoiceNumber}</Text>
            <Text style={s.muted}>Issued {data.issuedAt}</Text>
            {paid && <Text style={s.paidBadge}>PAID{data.paidAt ? ` · ${data.paidAt}` : ""}</Text>}
          </View>
        </View>

        <View style={{ marginTop: 24 }}>
          <Text style={s.muted}>Billed to</Text>
          <Text>{data.customerName}</Text>
          {data.address && <Text style={s.muted}>{data.address}</Text>}
          <Text style={{ marginTop: 6 }}>{data.serviceName}</Text>
        </View>

        <View style={s.table}>
          <View style={s.th}>
            <Text style={s.cDesc}>Description</Text>
            <Text style={s.cQty}>Qty</Text>
            <Text style={s.cUnit}>Unit</Text>
            <Text style={s.cAmt}>Amount</Text>
          </View>
          {data.lineItems.map((item, i) => (
            <View style={s.tr} key={i}>
              <Text style={s.cDesc}>{item.description}</Text>
              <Text style={s.cQty}>{item.quantity}</Text>
              <Text style={s.cUnit}>{aud(item.unit_price_cents)}</Text>
              <Text style={s.cAmt}>{aud(item.total_cents)}</Text>
            </View>
          ))}
        </View>

        <View style={s.totals}>
          <View style={s.totalRow}>
            <Text style={s.muted}>Subtotal (ex GST)</Text>
            <Text>{aud(data.subtotalCents)}</Text>
          </View>
          <View style={s.totalRow}>
            <Text style={s.muted}>GST (10%)</Text>
            <Text>{aud(data.gstCents)}</Text>
          </View>
          <View style={s.grand}>
            <Text>Total</Text>
            <Text>{aud(data.totalCents)}</Text>
          </View>
        </View>

        <Text style={s.footer}>
          {paid
            ? "Thank you — payment received in full."
            : "Payment due on completion. Pay the installer on site or by bank transfer."}{" "}
          Generated by {BUSINESS.name}.
        </Text>
      </Page>
    </Document>
  );
}
